---
title: "T-test"
author: "Samuel Zakka Bako"
date: "10/31/2019"
output: html_document
---
```{r}
dt<-read.csv("C:/Users/user/Desktop/R/Session2/data/diamond.csv", header = T)
```
```{r}
dt
```
```{r}
str(dt)
```

```{r}
d<-read.csv("C:/Users/user/Desktop/R/Session2/data/cancer.csv", header = T)
d
```

```{r}
t.test(d$area_se~d$diagnosis, alternative="two.sided")

```

```{r}
x<-c(239, 170,182, 143,141, 170, 160, 154, 185, 130)
y<-c(362, 343, 330, 340, 314, 567, 292, 439, 312, 292)
paired_1<-t.test(x, y, paired=TRUE)
paired_1
```

```{r}
sam <-read.csv("C:/Users/user/Desktop/R/dnew.csv", header = T)
sam
```
```{r}
sam1<- table(sam)
sam1
```

```{r}
chisq.test(sam1)
```

```{r}
write.csv(sam1, file = "sam1.csv")
```
```{r}
a1<-aov(cht$price~cht$color)
summary(a1)
```

(3932.8-3000)/(3989.44/sqrt(53940))
 t.test(dt$price, mu=3000, alternative = "less")
 

```{r}
data("iris")
fix(iris)
str(iris)
```

```{r}
library(ggplot2)
```
#ploting graph in R
```{r}
dat<-ggplot(iris, aes(y = Sepal.Length, x = Petal.Length)) + geom_point(aes(colour = "red")) + labs(title = "Relationship between setal length and petal length")
dat
```
```{r}
ml<-lm(Sepal.Length~Petal.Length, data = iris)
summary(ml)
```
#How to plot Histogram in R
```{r}
data("iris")
attach(iris)
ml<-lm(Sepal.Length~Petal.Length)
hist(ml$residuals)
```

```{r}
par(mfrow = c(2,2))
plot(ml)
```
m1<-lm(Sepal.Length~Petal.Length, data = iris[-c(15,136,107,128,16)])
summary(ml)
```
```